# Generated by Django 4.1.4 on 2023-07-31 21:18

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='file',
            field=models.ImageField(default=None, help_text='Maximum file size allowed is 1Mb', upload_to=apps.base.models.file_city, validators=[apps.base.models.Cities.validate_image]),
        ),
        migrations.AddField(
            model_name='cities',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='name_fa',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='name_fa',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
