# Generated by Django 4.1.4 on 2023-07-31 21:19

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cities_file_cities_name_en_cities_name_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='file',
            field=models.ImageField(blank=True, default=None, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.base.models.file_city, validators=[apps.base.models.Cities.validate_image]),
        ),
    ]
