# Generated by Django 4.1.4 on 2023-07-31 21:20

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_cities_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='file',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.base.models.file_city, validators=[apps.base.models.Cities.validate_image]),
        ),
    ]
