# Generated by Django 4.1.4 on 2023-06-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_forgot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
