# Generated by Django 4.1.4 on 2023-06-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
