# Generated by Django 4.1.4 on 2023-07-04 00:15

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.base.models.file_category, validators=[apps.base.models.Slider.validate_image])),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('active', models.SmallIntegerField(default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
    ]
