# Generated by Django 4.1.4 on 2023-07-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, help_text='some tag, hoteltik, international, etc...')),
                ('keywords_fa', models.TextField(blank=True, help_text='some tag, hoteltik, international, etc...', null=True)),
                ('keywords_en', models.TextField(blank=True, help_text='some tag, hoteltik, international, etc...', null=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Seo',
                'verbose_name_plural': 'Seo',
            },
        ),
    ]
