# Generated by Django 4.1.4 on 2023-08-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cities_latitude_alter_cities_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(1, 'کد پستی'), (2, 'تلفن'), (3, 'ایمبل'), (4, 'اینستاگرام'), (5, 'واتس اپ'), (6, 'تلگرام')], max_length=128, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوتر',
            },
        ),
    ]
