# Generated by Django 4.1.4 on 2023-07-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='description_fa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
