# Generated by Django 4.1.4 on 2023-08-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='name',
            field=models.SmallIntegerField(choices=[(1, 'کد پستی'), (2, 'تلفن'), (3, 'ایمبل'), (4, 'اینستاگرام'), (5, 'واتس اپ'), (6, 'تلگرام')], null=True),
        ),
    ]
