# Generated by Django 4.1.4 on 2023-07-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_meta_description_alter_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Meta'},
        ),
    ]
