# Generated by Django 4.1.4 on 2023-08-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_footer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='name',
            field=models.CharField(choices=[('postal_code', 'کد پستی'), ('phone', 'تلفن'), ('email', 'ایمبل'), ('instagram', 'اینستاگرام'), ('whatsapp', 'واتس اپ'), ('telegram', 'تلگرام')], max_length=255, null=True),
        ),
    ]
