# Generated by Django 4.1.4 on 2023-07-18 20:34

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_provinces_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر'},
        ),
        migrations.AlterModelOptions(
            name='forgot_password',
            options={'verbose_name': 'فراموشی پسورد'},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': 'متا', 'verbose_name_plural': 'متا'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مشتری'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='file',
            field=models.ImageField(blank=True, help_text='جداکثر حجم فایل 1MB', null=True, upload_to=apps.base.models.file_category, validators=[apps.base.models.Slider.validate_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ادمین'), (2, 'مشتری')], default=2),
        ),
    ]
