# Generated by Django 4.1.4 on 2023-08-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_footer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='page_name',
            field=models.CharField(blank=True, choices=[('همه هتل ها', 'hotels'), ('صفحه اصلی', 'home_page'), ('درباره ما', 'about_us_page'), ('قوانین و مقررات', 'general_policy_page'), ('سبد خرید', 'cart_page')], max_length=255),
        ),
    ]
