# Generated by Django 4.1.4 on 2023-07-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_cities_options_alter_forgot_password_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgot_password',
            options={'verbose_name': 'فراموشی پسورد', 'verbose_name_plural': 'فراموشی پسورد'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری'},
        ),
    ]
