# Generated by Django 4.1.4 on 2023-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_meta_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='page_name',
            field=models.CharField(blank=True, choices=[('hotels', 'همه هتل ها'), ('home_page', 'صفحه اصلی'), ('about_us_page', 'درباره ما'), ('general_policy_page', 'قوانین و مقررات'), ('cart_page', 'سبد خرید')], max_length=255),
        ),
    ]
