# Generated by Django 4.1.4 on 2023-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_meta_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, choices=[('about-us', 'همه هتل ها'), ('general_policy_page', 'قوانین و مقررات')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'صفحه ها',
                'verbose_name_plural': 'صفحه ها',
            },
        ),
    ]
