# Generated by Django 4.1.4 on 2023-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(blank=True, choices=[('about-us', 'درباره ما'), ('general_policy_page', 'قوانین و مقررات')], max_length=255),
        ),
    ]
