# Generated by Django 4.1.4 on 2023-08-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_pages_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('new', 'شرط برای هتل جدید')], max_length=255)),
                ('value', models.CharField(blank=True, choices=[('new', 'شرط برای هتل جدید')], max_length=255)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'کانفیگ',
                'verbose_name_plural': 'کانفیگ',
            },
        ),
    ]
