# Generated by Django 4.1.4 on 2023-08-11 13:00

import apps.base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_alter_configuration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='file',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.base.models.file_city, validators=[apps.base.models.Cities.validate_image], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='provinces',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.provinces', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, choices=[('new', 'شرط برای هتل جدید')], max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='name',
            field=models.CharField(choices=[('postal_code', 'کد پستی'), ('phone', 'تلفن'), ('email', 'ایمبل'), ('instagram', 'اینستاگرام'), ('whatsapp', 'واتس اپ'), ('telegram', 'تلگرام')], max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='forgot_password',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='forgot_password',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='forgot_password',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='forgot_password',
            name='token',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='forgot_password',
            name='user',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='keywords',
            field=models.TextField(blank=True, help_text='some tag, hoteltik, international, etc...', verbose_name='کلید واژه'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='some tag, hoteltik, international, etc...', null=True, verbose_name='کلید واژه'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='keywords_fa',
            field=models.TextField(blank=True, help_text='some tag, hoteltik, international, etc...', null=True, verbose_name='کلید واژه'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='page_name',
            field=models.CharField(blank=True, choices=[('hotels', 'همه هتل ها'), ('home_page', 'صفحه اصلی'), ('about_us_page', 'درباره ما'), ('general_policy_page', 'قوانین و مقررات'), ('cart_page', 'سبد خرید')], max_length=255, verbose_name='نام صفحه'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(blank=True, choices=[('about-us', 'درباره ما'), ('general_policy_page', 'قوانین و مقررات')], max_length=255, verbose_name='نام صفحه'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='عرض'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='active',
            field=models.SmallIntegerField(default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
