# Generated by Django 4.1.4 on 2023-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_cities_created_at_alter_cities_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='نام استان'),
        ),
    ]
