# Generated by Django 4.1.4 on 2023-08-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_cities_name_alter_cities_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_fa',
        ),
    ]
