# Generated by Django 4.1.4 on 2023-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_slider_title_remove_slider_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, null=True, verbose_name='کد')),
                ('receiver', models.CharField(max_length=128, null=True, verbose_name='دریافت کننده')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='نوع')),
                ('message', models.TextField(null=True, verbose_name='متن')),
                ('status_code', models.SmallIntegerField(null=True, verbose_name='کد برگشتی')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیامک ها',
                'verbose_name_plural': 'پیامک ها',
            },
        ),
    ]
