# Generated by Django 4.1.4 on 2023-07-06 14:28

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('title_fa', models.CharField(max_length=256, null=True)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('desc', models.TextField(null=True)),
                ('desc_fa', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('flag', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='اگر Yes باشد در هدر سایت در بخش بلاگ ها نمایش داده خواهد شد!')),
                ('active', models.SmallIntegerField(default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Category Blog',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.blog.models.file_category, validators=[apps.blog.models.Files.validate_image])),
                ('title', models.CharField(max_length=256, null=True)),
                ('title_fa', models.CharField(max_length=256, null=True)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('note', models.CharField(max_length=256, null=True)),
                ('note_fa', models.CharField(max_length=256, null=True)),
                ('note_en', models.CharField(max_length=256, null=True)),
                ('active', models.SmallIntegerField(default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog File',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=256)),
                ('title_fa', models.CharField(default=0, max_length=256, null=True)),
                ('title_en', models.CharField(default=0, max_length=256, null=True)),
                ('desc', models.TextField(null=True)),
                ('desc_fa', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('active', models.SmallIntegerField(default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('category_blog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('default_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.files')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
