# Generated by Django 4.1.4 on 2023-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='files',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='main',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
