# Generated by Django 4.1.4 on 2023-07-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'فایل های بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'بلاگ'},
        ),
    ]
