# Generated by Django 4.1.4 on 2023-08-11 12:52

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_active_alter_files_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc_fa',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='اگر Yes باشد در هدر سایت در بخش بلاگ ها نمایش داده خواهد شد!', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='files',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='files',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='files',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.blog.models.file_category, validators=[apps.blog.models.Files.validate_image], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='files',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='files',
            name='note_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='files',
            name='note_fa',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_fa',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='main',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='main',
            name='category_blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='main',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='main',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='main',
            name='default_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.files', verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='main',
            name='desc',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='main',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='main',
            name='desc_fa',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(default=0, max_length=256, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='main',
            name='title_en',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='main',
            name='title_fa',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='عنوان'),
        ),
    ]
