# Generated by Django 4.1.4 on 2023-07-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_files_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی بلاگ', 'verbose_name_plural': 'دسته بندی بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'فایل های بلاگ', 'verbose_name_plural': 'فایل های بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'بلاگ', 'verbose_name_plural': 'بلاگ'},
        ),
    ]
