# Generated by Django 4.1.4 on 2023-08-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_active_alter_category_date_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='note',
        ),
        migrations.RemoveField(
            model_name='files',
            name='note_en',
        ),
        migrations.RemoveField(
            model_name='files',
            name='note_fa',
        ),
    ]
