# Generated by Django 4.1.4 on 2023-07-21 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, default=None, null=True)),
                ('check_out', models.DateField(blank=True, default=None, null=True)),
                ('secure_key', models.CharField(default=0, max_length=256)),
                ('flag', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Delete')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارت',
                'verbose_name_plural': 'کارت',
            },
        ),
        migrations.CreateModel(
            name='Cart_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('check_in_flag', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('check_out_flag', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('extra_person_quantity', models.SmallIntegerField(default=0)),
                ('flag', models.SmallIntegerField(choices=[(1, 'فعال'), (2, 'منقضی شد'), (3, 'پرداخت شده')], default=1)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='front.cart')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='hotel.room')),
            ],
            options={
                'verbose_name': 'جزئیات کارت',
                'verbose_name_plural': 'جزئیات کارت',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256, null=True)),
                ('current_state', models.SmallIntegerField(default=1)),
                ('payment_type', models.SmallIntegerField(default=1)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_products', models.SmallIntegerField(default=1)),
                ('has_invoice', models.BooleanField(blank=True, choices=[(True, 'دارم'), (False, 'ندارم')], default=None, null=True)),
                ('agree_rule', models.BooleanField(blank=True, choices=[(True, 'دارم'), (False, 'ندارم')], default=None, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='front.cart')),
                ('hotel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotel.hotel')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش ها',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField(default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='front.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=256)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('check_in_flag', models.SmallIntegerField(default=0)),
                ('check_out_flag', models.SmallIntegerField(default=0)),
                ('extra_person_quantity', models.SmallIntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_price_dis_incl', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_price_dis_excl', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reduction_type', models.SmallIntegerField(default=1)),
                ('total_products', models.SmallIntegerField()),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='front.order')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='hotel.room')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش ها',
                'verbose_name_plural': 'جزئیات سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default=None, max_length=256, null=True)),
                ('mobile', models.CharField(default=None, max_length=256, null=True)),
                ('nationality', models.SmallIntegerField(choices=[(1, 'ایرانی'), (2, 'غیر ایرانی')], null=True)),
                ('flag', models.SmallIntegerField(choices=[(2, 'Done'), (3, 'Delete')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart_detail', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='front.cart_detail')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='hotel.room')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافر',
            },
        ),
    ]
