# Generated by Django 4.1.4 on 2023-07-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_discount_room'),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_temp',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='secure_key',
        ),
        migrations.RemoveField(
            model_name='cart_temp',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_temp',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart_temp',
            name='room',
        ),
        migrations.AlterField(
            model_name='cart_temp',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Delete')], default=0),
        ),
        migrations.CreateModel(
            name='Cart_detail_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart_temp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='front.cart_temp')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
