# Generated by Django 4.1.4 on 2023-08-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='front.order'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='hotel.room'),
        ),
    ]
