# Generated by Django 4.1.4 on 2023-08-06 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0002_alter_order_detail_order_alter_order_detail_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان تخفیف')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='کد تخفیف')),
                ('date_from', models.DateTimeField(default=0, null=True, verbose_name='تاریخ شروع')),
                ('date_to', models.DateTimeField(default=0, null=True, verbose_name='تاریخ پایان')),
                ('quantity', models.SmallIntegerField(default=0, null=True, verbose_name='موجودی')),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='حداقل مبلغ خرید')),
                ('reduction_type', models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار')], default=1, verbose_name='نوع تخفیف')),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='مقدار')),
                ('highlight', models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=0, verbose_name='نمایان برای مشتری')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخفیف مشتریان',
                'verbose_name_plural': 'تخفیف مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Order_cart_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='حداقل مبلغ خرید')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart_rule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.cart_rule')),
                ('order', models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.order')),
            ],
            options={
                'verbose_name': 'تخفیفات ثبت شده',
                'verbose_name_plural': 'تخفیفات ثبت شده',
            },
        ),
        migrations.CreateModel(
            name='Cart_cart_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.cart')),
                ('cart_rule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.cart_rule')),
            ],
            options={
                'verbose_name': 'تخفیف مشتریان',
                'verbose_name_plural': 'تخفیف مشتریان',
            },
        ),
    ]
