# Generated by Django 4.1.4 on 2023-08-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_cart_rule_order_cart_rule_cart_cart_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_cart_rule',
            name='cart_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.cart_rule'),
        ),
    ]
