# Generated by Django 4.1.4 on 2023-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_cart_temp_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_detail_temp',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Delete')], default=1),
        ),
    ]
