# Generated by Django 4.1.4 on 2023-07-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_cart_detail_temp_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_temp',
            name='hotel',
        ),
        migrations.AlterModelOptions(
            name='cart_detail',
            options={'verbose_name': 'Cart Detail', 'verbose_name_plural': 'Cart Detail'},
        ),
        migrations.RemoveField(
            model_name='cart_detail',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='cart_detail',
            name='session_key',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='cart',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Delete')], default=1),
        ),
        migrations.DeleteModel(
            name='Cart_detail_temp',
        ),
        migrations.DeleteModel(
            name='Cart_temp',
        ),
    ]
