# Generated by Django 4.1.4 on 2023-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_cart_cart_rule_cart_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_rule',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='کد تخفیف'),
        ),
    ]
