# Generated by Django 4.1.4 on 2023-08-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_alter_cart_rule_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_rule',
            old_name='date_to',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='cart_rule',
            old_name='date_from',
            new_name='start_date',
        ),
    ]
