# Generated by Django 4.1.4 on 2023-07-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_remove_cart_temp_hotel_alter_cart_detail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_key',
            new_name='secure_key',
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
