# Generated by Django 4.1.4 on 2023-08-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_rename_date_to_cart_rule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cart_rule',
            name='cart_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.cart_rule'),
        ),
    ]
