# Generated by Django 4.1.4 on 2023-08-08 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_alter_order_cart_rule_cart_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='cart_detail',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='front.cart_detail'),
        ),
    ]
