# Generated by Django 4.1.4 on 2023-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_detail',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'فعال'), (2, 'منقضی شد'), (3, 'پرداخت شده')], default=1),
        ),
    ]
