# Generated by Django 4.1.4 on 2023-08-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_alter_guest_cart_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='cart_detail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='front.cart_detail'),
        ),
    ]
