# Generated by Django 4.1.4 on 2023-07-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_discount_room'),
        ('front', '0008_cart_detail_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_in',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cart',
            name='check_out',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='front.cart'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='hotel.room'),
        ),
    ]
