# Generated by Django 4.1.4 on 2023-08-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('front', '0009_alter_guest_cart_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Cart_guest',
        ),
        migrations.CreateModel(
            name='Order_detail_guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default=None, max_length=255, null=True)),
                ('mobile', models.CharField(default=None, max_length=255, null=True)),
                ('nationality', models.SmallIntegerField(choices=[(1, 'ایرانی'), (2, 'غیر ایرانی')], null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_detail', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_guest', to='front.order_detail')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_guest', to='hotel.room')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافر',
            },
        ),
    ]
