# Generated by Django 4.1.4 on 2023-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_cart_check_in_cart_check_out_alter_cart_detail_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='check_in',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='check_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
