# Generated by Django 4.1.4 on 2023-08-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('front', '0010_rename_guest_cart_guest_order_detail_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_guest',
            name='cart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_guest', to='front.cart'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='cart_detail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_guest', to='front.cart_detail'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_guest', to='hotel.room'),
        ),
    ]
