# Generated by Django 4.1.4 on 2023-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_alter_cart_check_in_alter_cart_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='check_in',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='check_out',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
