# Generated by Django 4.1.4 on 2023-07-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_alter_cart_check_in_alter_cart_check_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'کارت', 'verbose_name_plural': 'کارت'},
        ),
        migrations.AlterModelOptions(
            name='cart_detail',
            options={'verbose_name': 'جزئیات کارت', 'verbose_name_plural': 'جزئیات کارت'},
        ),
    ]
