# Generated by Django 4.1.4 on 2023-08-10 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0011_cart_guest_cart_alter_cart_guest_cart_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agree_rule',
            field=models.BooleanField(blank=True, choices=[(True, 'دارم'), (False, 'ندارم')], default=None, null=True, verbose_name='قبول قوانین'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='front.cart', verbose_name='سبد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_in_out_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ ورود و خروح'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_state',
            field=models.SmallIntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید از سوی کارمندان')], default=1, verbose_name='وضعیت فعلی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_person_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ نفر اضافه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_invoice',
            field=models.BooleanField(blank=True, choices=[(True, 'دارم'), (False, 'ندارم')], default=None, null=True, verbose_name='فاکتور رسمی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotel.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(1, 'رزرو'), (2, 'فیش بانکی'), (3, 'آنلاین')], default=1, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=255, null=True, verbose_name='رفرنس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount_dis_excl',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='قیمت بدون تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount_dis_incl',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_room',
            field=models.SmallIntegerField(default=1, verbose_name='تعدا اتاق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
    ]
