# Generated by Django 4.1.4 on 2023-07-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_alter_breakfast_rate_hotel_and_more'),
        ('front', '0012_alter_cart_options_alter_cart_detail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_detail',
            name='check_in_flag',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='cart_detail',
            name='check_out_flag',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='cart_detail',
            name='extra_person_quantity',
            field=models.SmallIntegerField(default=0),
        ),

    ]
