# Generated by Django 4.1.4 on 2023-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_alter_order_agree_rule_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
    ]
