# Generated by Django 4.1.4 on 2023-07-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_alter_breakfast_rate_hotel_and_more'),
        ('front', '0013_cart_detail_check_in_flag_cart_detail_check_out_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default=None, max_length=256, null=True)),
                ('mobile', models.CharField(default=None, max_length=256, null=True)),
                ('nationality', models.SmallIntegerField(choices=[(1, 'ایرانی'), (2, 'غیر ایرانی')], null=True)),
                ('flag', models.SmallIntegerField(choices=[(2, 'Done'), (3, 'Delete')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart_detail', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='front.cart_detail')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='hotel.room')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافر',
            },
        ),
    ]
