# Generated by Django 4.1.4 on 2023-08-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_alter_order_date_add_alter_order_date_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='front.order'),
        ),
    ]
