# Generated by Django 4.1.4 on 2023-08-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('front', '0014_alter_order_detail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='hotel.room'),
        ),
    ]
