# Generated by Django 4.1.4 on 2023-08-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_alter_order_detail_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ پرداخت شده'),
        ),
    ]
