# Generated by Django 4.1.4 on 2023-07-21 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0029_alter_breakfast_rate_rate_and_more'),
        ('front', '0015_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256, null=True, unique=True)),
                ('current_state', models.SmallIntegerField(default=1)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_products', models.SmallIntegerField(default=1)),
                ('has_invoice', models.SmallIntegerField(choices=[(1, 'YES'), (2, 'NO')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='front.cart')),
                ('hotel', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotel.hotel')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش ها',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=256)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('check_in_flag', models.SmallIntegerField(default=0)),
                ('check_out_flag', models.SmallIntegerField(default=0)),
                ('extra_person_quantity', models.SmallIntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_price_dis_incl', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_price_dis_excl', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('reduction_type', models.SmallIntegerField(default=1)),
                ('total_products', models.SmallIntegerField()),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='front.order')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='hotel.room')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش ها',
                'verbose_name_plural': 'جزئیات سفارش ها',
            },
        ),
    ]
