# Generated by Django 4.1.4 on 2023-08-11 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0016_alter_order_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='check_in',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='ورود'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='check_out',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='خروج'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Done'), (3, 'Delete')], default=1, verbose_name='فلگ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='secure_key',
            field=models.CharField(default=0, max_length=255, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='cart_cart_rule',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.cart'),
        ),
        migrations.AlterField(
            model_name='cart_cart_rule',
            name='cart_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.cart_rule'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_detail', to='front.cart', verbose_name='کارت'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='check_in_flag',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='ورود زود هنگام'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='check_out_flag',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='خروج دیر هتگام'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='extra_person_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='نفر اضافه'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'فعال'), (2, 'منقضی شد'), (3, 'پرداخت شده')], default=1, verbose_name='فلگ'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_detail', to='hotel.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_guest', to='front.cart', verbose_name='کارت'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='cart_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_guest', to='front.cart_detail', verbose_name='جزئیات کارت'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='flag',
            field=models.SmallIntegerField(choices=[(2, 'Done'), (3, 'Delete')], default=1, verbose_name='فلگ'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='fullname',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='mobile',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='nationality',
            field=models.SmallIntegerField(choices=[(1, 'ایرانی'), (2, 'غیر ایرانی')], null=True, verbose_name='ملیت'),
        ),
        migrations.AlterField(
            model_name='cart_guest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_guest', to='hotel.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='cart_rule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='front.cart', verbose_name='سبد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='hotel.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='order_cart_rule',
            name='cart_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.cart_rule'),
        ),
        migrations.AlterField(
            model_name='order_cart_rule',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.order'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='check_in_flag',
            field=models.SmallIntegerField(default=0, verbose_name='ورود زود هنگام'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='check_out_flag',
            field=models.SmallIntegerField(default=0, verbose_name='خروج دیر هنگام'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='extra_person_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='افراد اضافه'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='front.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='hotel.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='total_price_dis_excl',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='قیمت بدون تخفیف'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='total_price_dis_incl',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='order_detail_guest',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order_detail_guest',
            name='fullname',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='order_detail_guest',
            name='mobile',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='order_detail_guest',
            name='nationality',
            field=models.SmallIntegerField(choices=[(1, 'ایرانی'), (2, 'غیر ایرانی')], null=True, verbose_name='ملیت'),
        ),
        migrations.AlterField(
            model_name='order_detail_guest',
            name='order_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail_guest', to='front.order_detail', verbose_name='جزئیات سفارش'),
        ),
        migrations.AlterField(
            model_name='order_detail_guest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail_guest', to='hotel.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='step',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step', to='front.cart'),
        ),
    ]
