# Generated by Django 4.1.4 on 2023-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_order_payment_type_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agree_rule',
            field=models.SmallIntegerField(choices=[(1, 'YES'), (2, 'NO')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_invoice',
            field=models.SmallIntegerField(choices=[(1, 'YES'), (2, 'NO')], default=0),
        ),
    ]
