# Generated by Django 4.1.4 on 2023-08-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_remove_order_detail_base_price_alter_cart_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='فیمت پایه'),
        ),
    ]
