# Generated by Django 4.1.4 on 2023-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_order_agree_rule_alter_order_has_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agree_rule',
            field=models.SmallIntegerField(choices=[(1, 'YES'), (2, 'NO')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='has_invoice',
            field=models.SmallIntegerField(choices=[(1, 'YES'), (2, 'NO')], default=2),
        ),
    ]
