# Generated by Django 4.1.4 on 2023-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_order_detail_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, 'در انتظار تکمیل'), (2, 'سفارش'), (3, 'حذف')], default=1, verbose_name='فلگ'),
        ),
        migrations.AlterField(
            model_name='cart_rule',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cart_rule',
            name='date_upd',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت'),
        ),
        migrations.AlterField(
            model_name='order_cart_rule',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
