# Generated by Django 4.1.4 on 2023-08-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_alter_cart_flag_alter_cart_rule_date_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_rule',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان تخفیف'),
        ),
        migrations.AddField(
            model_name='cart_rule',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان تخفیف'),
        ),
    ]
