# Generated by Django 4.1.4 on 2023-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_cart_rule_title_en_cart_rule_title_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_rule',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='کد تخفیف'),
        ),
    ]
