# Generated by Django 4.1.4 on 2023-08-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_alter_cart_rule_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptOrder',
            fields=[
            ],
            options={
                'verbose_name': 'رزرو تایید شده',
                'verbose_name_plural': 'رزرو تایید شده',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('front.order',),
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'رزرو موقت',
                'verbose_name_plural': 'رزرو موقت',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('front.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_state',
            field=models.SmallIntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شد'), (3, 'ارسال رسید به هتل ها')], default=1, verbose_name='وضعیت فعلی'),
        ),
    ]
