# Generated by Django 4.1.4 on 2023-08-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_acceptorder_pendingorder_alter_order_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_in',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='ورود'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_out',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='خروج'),
        ),
    ]
