# Generated by Django 4.1.4 on 2023-07-21 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_alter_breakfast_rate_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0022_alter_order_agree_rule_alter_order_has_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
