# Generated by Django 4.1.4 on 2023-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_alter_order_hotel_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
