# Generated by Django 4.1.4 on 2023-09-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_order_check_in_order_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail_guest',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail_guest', to='front.order_detail', verbose_name='جزئیات سفارش'),
        ),
    ]
