# Generated by Django 4.1.4 on 2023-07-30 12:43

import apps.hotel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.hotel.models.file, validators=[apps.hotel.models.Cover.validate_image])),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'کاور هتل ها',
                'verbose_name_plural': 'کاور هتل ها',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='نام هتل')),
                ('reference', models.CharField(max_length=255, null=True, unique=True, verbose_name='رفرنس')),
                ('long_desc', models.TextField(null=True, verbose_name='توضیحات بلند')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('rule_cancelable', models.TextField(blank=True, null=True, verbose_name='قوانین کنسل')),
                ('rule_enter', models.TextField(blank=True, null=True, verbose_name='قوانین ورود و خروج')),
                ('note', models.TextField(blank=True, null=True, verbose_name='نوت')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True, verbose_name='شماره تلفن')),
                ('number_rooms', models.SmallIntegerField(default=0, verbose_name='تعداد اتاق ها')),
                ('number_floor', models.SmallIntegerField(default=0, verbose_name='تعداد طبقه')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (4, '3'), (4, '4'), (5, '5')], default=1, verbose_name='ستاره ها')),
                ('meta_keywords', models.CharField(blank=True, default=None, help_text='some tag, espinas, international, etc...', max_length=255, verbose_name='متا کیبورد')),
                ('has_early_check_in_out', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='دارای ورود و خروج زود هنگام')),
                ('has_breakfast', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='دارای صبحانه')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('upd_add', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cities', verbose_name='شهر')),
                ('default_cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.cover', verbose_name='عکس پیش فرض')),
            ],
            options={
                'verbose_name': 'هتل ها',
                'verbose_name_plural': 'هتل ها',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (4, '3'), (4, '4'), (5, '5')], default=0)),
                ('title', models.CharField(default=None, max_length=255, verbose_name='عنوان')),
                ('short_desc', models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کوتاه')),
                ('desc_good', models.TextField(blank=True, null=True, verbose_name='نکات مثبت')),
                ('desc_bad', models.TextField(blank=True, null=True, verbose_name='نکات منفی')),
                ('active', models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دیدگاه ها',
                'verbose_name_plural': 'دیدگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت پابه')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('short_desc', models.TextField(null=True, verbose_name='توضیحات کوتاه')),
                ('note', models.TextField(null=True, verbose_name='نوت')),
                ('number_floor', models.SmallIntegerField(default=0, verbose_name='طبقه اتاق')),
                ('count', models.SmallIntegerField(default=0, verbose_name='تعداد اتاق')),
                ('capacity', models.SmallIntegerField(default=0, verbose_name='ظرفیت')),
                ('extra_person', models.SmallIntegerField(default=0, verbose_name='نفر اضافه')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('upd_add', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'اتاق ها',
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='Room_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.hotel.models.file_room, validators=[apps.hotel.models.Room_cover.validate_image])),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'کاور اتاق ها',
                'verbose_name_plural': 'کاور اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='Room_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default=None, help_text='Maximum file size allowed is 1Mb', upload_to=apps.hotel.models.file_room, validators=[apps.hotel.models.Room_images.validate_image])),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'تصاویر اتاق ها',
                'verbose_name_plural': 'تصاویر اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='Room_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('note', models.CharField(blank=True, default=None, max_length=255, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'امکانات اتاق ها',
                'verbose_name_plural': 'امکانات اتاق ها',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='default_cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room_cover', verbose_name='عکس پس زمینه'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.CreateModel(
            name='Reviews_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کوتاه')),
                ('active', models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0, verbose_name='وضعبت')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviews', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.reviews')),
            ],
            options={
                'verbose_name': 'جواب دیدگاه ها',
                'verbose_name_plural': 'جواب دیدگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default=None, help_text='Maximum file size allowed is 1Mb', upload_to=apps.hotel.models.file, validators=[apps.hotel.models.Images.validate_image])),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'عکس های هتل ها',
                'verbose_name_plural': 'عکس های هتل ها',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('note', models.CharField(blank=True, default=None, max_length=255, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'امکانات  هتل ها',
                'verbose_name_plural': 'امکانات  هتل ها',
            },
        ),
        migrations.CreateModel(
            name='Extra_person_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('note', models.CharField(default=None, max_length=255, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_person_rate', to='hotel.hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'نفر اضافه',
                'verbose_name_plural': 'نفر اضافه',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان تخفیف')),
                ('reduction_type', models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار')], default=1, verbose_name='نوع تخفیف')),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='مقدار')),
                ('start_date', models.DateTimeField(default=0, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(default=0, verbose_name='تاریخ پایان')),
                ('active', models.SmallIntegerField(choices=[(1, 'فعال'), (0, 'غیرفعال')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_discount', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'تخفیف ها',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='Close_spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=512, null=True, verbose_name='توضیحات کوتاه')),
                ('note', models.CharField(blank=True, default=None, max_length=512, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'مکان های نزدیک',
                'verbose_name_plural': 'مکان های نزدیک',
            },
        ),
        migrations.CreateModel(
            name='Check_in_out_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('note', models.CharField(default=None, max_length=255, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_out_rate', to='hotel.hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'نرخ ورود و خروج',
                'verbose_name_plural': 'نرخ ورود و خروج',
            },
        ),
        migrations.CreateModel(
            name='Breakfast_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('note', models.CharField(default=None, max_length=255, verbose_name='نوت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_rate', to='hotel.hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'نرخ صبحانه',
                'verbose_name_plural': 'نرخ صبحانه',
            },
        ),
    ]
