# Generated by Django 4.1.4 on 2023-07-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='نام هتل'),
        ),
    ]
