# Generated by Django 4.1.4 on 2023-08-11 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_alter_configuration_value'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast_rate',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_rate', to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_out_rate', to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='close_spots',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_discount', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_person_rate', to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cities', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='default_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.cover', verbose_name='عکس پیش فرض'),
        ),
        migrations.AlterField(
            model_name='images',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews_reply',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.reviews'),
        ),
        migrations.AlterField(
            model_name='room',
            name='default_cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room_cover', verbose_name='عکس پس زمینه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='room_facility',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='room_images',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
    ]
