# Generated by Django 4.1.4 on 2023-07-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('hotel', '0002_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast_rate',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='breakfast_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_rate', to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='breakfast_rate',
            name='note',
            field=models.CharField(default=None, max_length=256, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='breakfast_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_out_rate', to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='note',
            field=models.CharField(default=None, max_length=256, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='close_spots',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='close_spots',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='close_spots',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=512, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='close_spots',
            name='short_desc',
            field=models.CharField(max_length=512, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'فعال'), (0, 'غیرفعال')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=0, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='reduction_type',
            field=models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار')], default=1, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(default=0, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان تخفیف'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_person_rate', to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='note',
            field=models.CharField(default=None, max_length=256, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=256, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cities', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='default_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.cover', verbose_name='عکس پیش فرض'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_breakfast',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='دارای صبحانه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_early_check_in_out',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='دارای ورود و خروج زود هنگام'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='long_desc',
            field=models.TextField(null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meta_keywords',
            field=models.CharField(blank=True, default=None, help_text='some tag, espinas, international, etc...', max_length=256, verbose_name='متا کیبورد'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_floor',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_rooms',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد اتاق ها'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(max_length=256, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reference',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='رفرنس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rule_cancelable',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین کنسل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rule_enter',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین ورود و خروج'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='short_desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (4, '3'), (4, '4'), (5, '5')], default=1, verbose_name='ستاره ها'),
        ),
        migrations.AlterField(
            model_name='images',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='images',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='images',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='desc_bad',
            field=models.TextField(blank=True, null=True, verbose_name='نکات منفی'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='desc_good',
            field=models.TextField(blank=True, null=True, verbose_name='نکات مثبت'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='short_desc',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default=None, max_length=256, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='reviews_reply',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0, verbose_name='وضعبت'),
        ),
        migrations.AlterField(
            model_name='reviews_reply',
            name='short_desc',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(default=0, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='count',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='default_cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room_cover', verbose_name='عکس پس زمینه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_person',
            field=models.SmallIntegerField(default=0, verbose_name='نفر اضافه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='room',
            name='note',
            field=models.TextField(null=True, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_floor',
            field=models.SmallIntegerField(default=0, verbose_name='طبقه اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_desc',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='room_cover',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room_cover',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='room_cover',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='room_facility',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room_facility',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=256, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='room_facility',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='room_images',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room_images',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='نوت'),
        ),
        migrations.AlterField(
            model_name='room_images',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان'),
        ),
    ]
