# Generated by Django 4.1.4 on 2023-07-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Hotel Images', 'verbose_name_plural': 'Hotel Images'},
        ),
    ]
