# Generated by Django 4.1.4 on 2023-07-06 15:13

import apps.hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_images_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(default=None, help_text='Maximum file size allowed is 1Mb', upload_to=apps.hotel.models.file, validators=[apps.hotel.models.Images.validate_image]),
        ),
    ]
