# Generated by Django 4.1.4 on 2023-08-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_breakfast_rate_date_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='close_spots',
            name='note_en',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='close_spots',
            name='note_fa',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='close_spots',
            name='short_desc_en',
            field=models.CharField(max_length=512, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='close_spots',
            name='short_desc_fa',
            field=models.CharField(max_length=512, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='facility',
            name='note_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='facility',
            name='note_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='facility',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='facility',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_en',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_fa',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='long_desc_en',
            field=models.TextField(null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='long_desc_fa',
            field=models.TextField(null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default=None, help_text='some tag, espinas, international, etc...', max_length=255, null=True, verbose_name='متا کیبورد'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_keywords_fa',
            field=models.CharField(blank=True, default=None, help_text='some tag, espinas, international, etc...', max_length=255, null=True, verbose_name='متا کیبورد'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام هتل'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام هتل'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='note_en',
            field=models.TextField(blank=True, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='note_fa',
            field=models.TextField(blank=True, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rule_cancelable_en',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین کنسل'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rule_cancelable_fa',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین کنسل'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rule_enter_en',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین ورود و خروج'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rule_enter_fa',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین ورود و خروج'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_desc_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='room',
            name='note_en',
            field=models.TextField(null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='room',
            name='note_fa',
            field=models.TextField(null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='room',
            name='short_desc_en',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='room',
            name='short_desc_fa',
            field=models.TextField(null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='room',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='room_facility',
            name='note_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='room_facility',
            name='note_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='نوت'),
        ),
        migrations.AddField(
            model_name='room_facility',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='room_facility',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
