# Generated by Django 4.1.4 on 2023-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_images_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
