# Generated by Django 4.1.4 on 2023-08-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_close_spots_note_en_close_spots_note_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='reference',
            field=models.CharField(max_length=255, null=True, verbose_name='رفرنس'),
        ),
    ]
