# Generated by Django 4.1.4 on 2023-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_images_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='close_spots',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='cover',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
