# Generated by Django 4.1.4 on 2023-07-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_close_spots_note_alter_cover_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='has_breakfast',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_early_check_in_out',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meta_keywords',
            field=models.CharField(blank=True, default=None, help_text='some tag, espinas, international, etc...', max_length=256),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rule_cancelable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rule_enter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Extra_person_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=256)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facility',
            },
        ),
    ]
