# Generated by Django 4.1.4 on 2023-07-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotel_has_breakfast_hotel_has_early_check_in_out_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra_person_rate',
            options={'verbose_name': 'Extra Person Rate', 'verbose_name_plural': 'Extra Person Rate'},
        ),
        migrations.RemoveField(
            model_name='extra_person_rate',
            name='title',
        ),
        migrations.AddField(
            model_name='extra_person_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='note',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.CreateModel(
            name='Check_in_out_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, max_length=256, null=True)),
                ('note', models.CharField(default=None, max_length=256)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Check In Out Rate',
                'verbose_name_plural': 'Check In Out Rate',
            },
        ),
        migrations.CreateModel(
            name='Breakfast_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, max_length=256, null=True)),
                ('note', models.CharField(default=None, max_length=256)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Breakfast Rate',
                'verbose_name_plural': 'Breakfast Rate',
            },
        ),
    ]
