# Generated by Django 4.1.4 on 2023-08-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_default_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='آدرس'),
        ),
    ]
