# Generated by Django 4.1.4 on 2023-08-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_hotel_address_alter_hotel_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'آنلاین'), (2, 'آفلاین')], default=1, verbose_name='نوع هتل'),
        ),
    ]
