# Generated by Django 4.1.4 on 2023-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_extra_person_rate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
