# Generated by Django 4.1.4 on 2023-08-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ آپدیت')),
                ('end_date', models.DateField(null=True, verbose_name='تاریخ آپدیت')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تقویم قیمت ها',
                'verbose_name_plural': 'تقویم قیمت ها',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date', to='hotel.date', verbose_name='تاریخ')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel', to='hotel.hotel', verbose_name='هتل')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='hotel.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'قیمت گذاری ها',
                'verbose_name_plural': 'قیمت گذاری ها',
            },
        ),
    ]
