# Generated by Django 4.1.4 on 2023-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_hotel_latitude_alter_hotel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
