# Generated by Django 4.1.4 on 2023-08-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_date_pricing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Calender_pricing',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='date',
        ),
        migrations.AddField(
            model_name='pricing',
            name='calender_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calender_pricing', to='hotel.calender_pricing', verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت هتل'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت مشتری'),
        ),
    ]
