# Generated by Django 4.1.4 on 2023-08-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_rename_date_calender_pricing_remove_pricing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_pricing', to='hotel.hotel', verbose_name='هتل'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_pricing', to='hotel.room', verbose_name='اتاق'),
        ),
    ]
