# Generated by Django 4.1.4 on 2023-07-07 00:13

import apps.hotel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_breakfast_rate_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('short_desc', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('number_floor', models.SmallIntegerField(default=0)),
                ('count', models.SmallIntegerField(default=0)),
                ('capacity', models.SmallIntegerField(default=0)),
                ('extra_person', models.SmallIntegerField(default=0)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0)),
                ('upd_add', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Room_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='Maximum file size allowed is 1Mb', null=True, upload_to=apps.hotel.models.file_room, validators=[apps.hotel.models.Room_cover.validate_image])),
                ('title', models.CharField(max_length=256, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Cover Room',
                'verbose_name_plural': 'Cover Room',
            },
        ),
        migrations.CreateModel(
            name='Room_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default=None, help_text='Maximum file size allowed is 1Mb', upload_to=apps.hotel.models.file_room, validators=[apps.hotel.models.Room_images.validate_image])),
                ('title', models.CharField(max_length=256, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'Room Images',
                'verbose_name_plural': 'Room Images',
            },
        ),
        migrations.CreateModel(
            name='Room_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=256)),
                ('active', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'Facility Room',
                'verbose_name_plural': 'Facility Room',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='default_cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room_cover'),
        ),
    ]
