# Generated by Django 4.1.4 on 2023-07-07 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_room_room_cover_room_images_room_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
