# Generated by Django 4.1.4 on 2023-08-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_room_base_price_remove_room_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricing',
            new_name='Room_pricing',
        ),
    ]
