# Generated by Django 4.1.4 on 2023-08-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_rename_pricing_room_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ آپدیت')),
                ('end_date', models.DateField(null=True, verbose_name='تاریخ آپدیت')),
                ('saturday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='شنبه')),
                ('sunday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='یکشنبه')),
                ('monday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='دوشنبه')),
                ('tuesday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='سه شنبه')),
                ('wednesday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='چهارشنبه')),
                ('thursday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='پنج شنبه')),
                ('friday', models.SmallIntegerField(choices=[(1, 'جا دارد'), (0, 'جا ندارد')], default=1, verbose_name='جمعه')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تقویم ظرفیت ها',
                'verbose_name_plural': 'تقویم ظرفیت ها',
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان تخفیف'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_breakfast',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='دارای صبحانه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_early_check_in_out',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='دارای ورود و خروج زود هنگام'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='long_desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='long_desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='long_desc_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_floor',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_rooms',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='تعداد اتاق ها'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'آنلاین'), (2, 'آفلاین')], default=1, verbose_name='نوع هتل'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_person',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='نفر اضافه'),
        ),
        migrations.AlterField(
            model_name='room_pricing',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت هتل'),
        ),
        migrations.CreateModel(
            name='Room_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('Calender_quantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calender_quantity', to='hotel.calender_quantity', verbose_name='تاریخ')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_quantity', to='hotel.hotel', verbose_name='هتل')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_quantity', to='hotel.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'ظرفیت ها',
                'verbose_name_plural': 'ظرفیت ها',
            },
        ),
    ]
