# Generated by Django 4.1.4 on 2023-07-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_room_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='hotel',
        ),
    ]
