# Generated by Django 4.1.4 on 2023-08-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_slider_title_remove_slider_title_en_and_more'),
        ('hotel', '0014_calender_quantity_alter_discount_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cities', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='default_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.cover', verbose_name='عکس پیش فرض'),
        ),
    ]
