# Generated by Django 4.1.4 on 2023-07-10 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (4, '3'), (4, '4'), (5, '5')], default=0)),
                ('title', models.TextField(default=None)),
                ('short_desc', models.TextField(blank=True, default=None, null=True)),
                ('desc_good', models.TextField(blank=True, null=True)),
                ('desc_bad', models.TextField(blank=True, null=True)),
                ('active', models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
