# Generated by Django 4.1.4 on 2023-08-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_hotel_active_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(default=0, verbose_name='ظرفیت'),
        ),
    ]
