# Generated by Django 4.1.4 on 2023-08-21 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_quantity',
            old_name='Calender_quantity',
            new_name='calender_quantity',
        ),
        migrations.RemoveField(
            model_name='room_pricing',
            name='active',
        ),
        migrations.RemoveField(
            model_name='room_pricing',
            name='base',
        ),
        migrations.RemoveField(
            model_name='room_pricing',
            name='hotel',
        ),
        migrations.AddField(
            model_name='calender_pricing',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_calender_pricing', to='hotel.hotel', verbose_name='هتل'),
        ),
        migrations.AddField(
            model_name='calender_pricing',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='calender_pricing',
            name='reduction_type',
            field=models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار')], default=1, verbose_name='نوع قیمت'),
        ),
        migrations.AddField(
            model_name='room_pricing',
            name='board',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت برد'),
        ),
        migrations.AlterField(
            model_name='calender_quantity',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='calender_quantity',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room_pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت هتل تیک'),
        ),
    ]
