# Generated by Django 4.1.4 on 2023-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_rename_calender_quantity_room_quantity_calender_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender_pricing',
            name='dis_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='calender_pricing',
            name='dis_reduction_type',
            field=models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار')], default=1, verbose_name='نوع تخفیف'),
        ),
    ]
