# Generated by Django 4.1.4 on 2023-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_calender_pricing_dis_reduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='flag_pricing',
            field=models.SmallIntegerField(choices=[(1, 1), (0, 0)], default=0, verbose_name='فعال'),
        ),
    ]
