# Generated by Django 4.1.4 on 2023-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_discount_flag_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender_pricing',
            name='dis_reduction_type',
            field=models.SmallIntegerField(choices=[(0, 'نیاز ندارم'), (1, 'درصد'), (2, 'مقدار')], default=0, verbose_name='نوع تخفیف'),
        ),
    ]
