# Generated by Django 4.1.4 on 2023-07-11 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0019_alter_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reviews_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(blank=True, default=None, null=True)),
                ('active', models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviews', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.reviews')),
            ],
            options={
                'verbose_name': 'Hotel Reviews Reply',
                'verbose_name_plural': 'Hotel Reviews Reply',
            },
        ),
    ]
