# Generated by Django 4.1.4 on 2023-08-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_calender_pricing_dis_reduction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='meta_keywords',
            field=models.CharField(blank=True, default=None, help_text='some tag, espinas, international, etc...', max_length=255, null=True, verbose_name='متا کیبورد'),
        ),
    ]
