# Generated by Django 4.1.4 on 2023-07-11 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_reviews_user_reviews_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction_type', models.SmallIntegerField(choices=[(1, 'درصد'), (2, 'مقدار')], default=1)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('start_date', models.DateTimeField(default=0)),
                ('end_date', models.DateTimeField(default=0)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
