# Generated by Django 4.1.4 on 2023-08-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_alter_hotel_meta_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender_pricing',
            name='title',
        ),
        migrations.RemoveField(
            model_name='calender_quantity',
            name='title',
        ),
        migrations.AlterField(
            model_name='calender_pricing',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='calender_pricing',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_breakfast',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'NO')], default=1, null=True, verbose_name='دارای صبحانه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='has_early_check_in_out',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'NO')], default=1, null=True, verbose_name='دارای ورود و خروج زود هنگام'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_floor',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_rooms',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد اتاق ها'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'آنلاین'), (2, 'آفلاین')], default=1, null=True, verbose_name='نوع هتل'),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_person',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='نفر اضافه'),
        ),
    ]
