# Generated by Django 4.1.4 on 2023-07-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'فعال'), (0, 'غیرفعال')], default=0),
        ),
    ]
