# Generated by Django 4.1.4 on 2023-08-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_remove_calender_pricing_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='default_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room_cover', verbose_name='عکس پس زمینه'),
        ),
    ]
