# Generated by Django 4.1.4 on 2023-07-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_discount_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Hotel Discount', 'verbose_name_plural': 'Hotel Discount'},
        ),
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
