# Generated by Django 4.1.4 on 2023-08-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_room_default_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_quantity',
            name='hotel',
        ),
        migrations.AddField(
            model_name='calender_quantity',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_calender_quantity', to='hotel.hotel', verbose_name='هتل'),
        ),
    ]
