# Generated by Django 4.1.4 on 2023-07-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_discount_options_discount_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
