# Generated by Django 4.1.4 on 2023-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_remove_room_quantity_hotel_calender_quantity_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_facility',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room_images',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'NO')], default=1, verbose_name='فعال'),
        ),
    ]
