# Generated by Django 4.1.4 on 2023-07-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_reviews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='room',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_discount', to='hotel.room'),
        ),
    ]
