# Generated by Django 4.1.4 on 2023-07-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_discount_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'هتل ها', 'verbose_name_plural': 'هتل ها'},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='available_for_order',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='on_sale',
        ),
    ]
