# Generated by Django 4.1.4 on 2023-08-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='flag_pricing',
            field=models.SmallIntegerField(choices=[(1, 1), (0, 0)], default=0, verbose_name='قیمت گذاری'),
        ),
        migrations.CreateModel(
            name='Discount_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='مقدار')),
                ('date_upd', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='hotel.discount', verbose_name='تخفیف')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_room', to='hotel.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'تخفیف اتاق ها',
                'verbose_name_plural': 'تخفیف اتاق ها',
            },
        ),
    ]
