# Generated by Django 4.1.4 on 2023-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_alter_hotel_options_remove_hotel_available_for_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast_rate',
            options={'verbose_name': 'نرخ صبحانه', 'verbose_name_plural': 'نرخ صبحانه'},
        ),
        migrations.AlterModelOptions(
            name='check_in_out_rate',
            options={'verbose_name': 'نرخ ورود و خروج', 'verbose_name_plural': 'نرخ ورود و خروج'},
        ),
        migrations.AlterModelOptions(
            name='close_spots',
            options={'verbose_name': 'مکان های نزدیک', 'verbose_name_plural': 'مکان های نزدیک'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name': 'کاور هتل ها', 'verbose_name_plural': 'کاور هتل ها'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف ها', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterModelOptions(
            name='extra_person_rate',
            options={'verbose_name': 'نفر اضافه', 'verbose_name_plural': 'نفر اضافه'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'امکانات  هتل ها', 'verbose_name_plural': 'امکانات  هتل ها'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'عکس های هتل ها', 'verbose_name_plural': 'عکس های هتل ها'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'دیدگاه ها', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='reviews_reply',
            options={'verbose_name': 'جواب ها دیدگاه ها', 'verbose_name_plural': 'جواب ها دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'اتاق ها', 'verbose_name_plural': 'اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='room_cover',
            options={'verbose_name': 'کاور اتاق ها', 'verbose_name_plural': 'کاور اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='room_facility',
            options={'verbose_name': 'امکانات اتاق ها', 'verbose_name_plural': 'امکانات اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='room_images',
            options={'verbose_name': 'تصاویر اتاق ها', 'verbose_name_plural': 'تصاویر اتاق ها'},
        ),
    ]
