# Generated by Django 4.1.4 on 2023-09-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0027_alter_discount_flag_pricing_discount_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='active',
            field=models.SmallIntegerField(choices=[(1, 'نمایان'), (0, 'مخفی')], default=0, verbose_name='وضعیت مشاهده'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
    ]
