# Generated by Django 4.1.4 on 2023-07-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_breakfast_rate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_rate', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_out_rate', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_person_rate', to='hotel.hotel'),
        ),
    ]
