# Generated by Django 4.1.4 on 2023-07-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_alter_breakfast_rate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast_rate',
            name='rate',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='check_in_out_rate',
            name='rate',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='reduction',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extra_person_rate',
            name='rate',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.TextField(default=0, null=True),
        ),
    ]
